# Site settings
title: Shablog
email: your-email@domain.com
description: >
    A collection of ponderous ponderings
baseurl: ""
url: "http://sabhiram.com"
twitter_username: sabhiram
github_username:  sabhiram

# Build settings
markdown: kramdown
