# Site settings
title: Shablog
email: mail@sabhiram.com
description: >
    A collection of ponderous ponderings
baseurl: ""
url: "http://sabhiram.com"
twitter_username: shaba_abhiram
github_username:  sabhiram

# Build settings
kramdown:
    input: GFM

defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
        openQuote: "<div class='sab-quote'>"
        closeQuote: "</div>"

  # This is here so we can enable the same defaults for "drafts" as well
  -
    scope:
        path: ""
        type: "drafts"
    values:
        layout: "post"
        openQuote: "<div class='sab-quote'>"
        closeQuote: "</div>"
